version: '3'
services:
  backend:
    build: ./backend
    ports:
      - '5000:5000'
    volumes:
      - ./backend:/app
    environment:
      - NODE_ENV=production

  frontend:
    build: ./frontend
    ports:
      - '3000:80'  # Mapear porta 3000 externa para 80 interna
    volumes:
      - ./frontend:/app
    environment:
      - NODE_ENV=production

