version: '3'
services:
  backend:
    build: ./backend
    ports:
      - '5000:5000'
    volumes:
      - ./backend:/app
    env_file: ./backend/.env

  frontend:
    build: ./frontend
    ports:
      - '3000:80'  # Mapear porta 3000 externa para 80 interna
    volumes:
      - ./frontend:/app
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://localhost:5000/api  # URL do backend
volumes:
  postgres-data:  # Volume para armazenar os dados do banco de forma persistente
