version: '3'
services:
  backend:
    build: ./backend
    ports:
      - '5000:5000'
    volumes:
      - ./backend:/app
    env_file: ./backend/.env

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
      target: production  # Use the 'production' stage from Dockerfile.prod for production
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://localhost:5000/api  # URL do backend
    restart: unless-stopped
    